### PR TITLE
Merging the slavikm fork back into master

### PR DESCRIPTION
**Pull request by glaslos**
I took @slavikm 's fork and merged your master on top of it. This replaces #9

### CODE REVIEW

**Comment by williballenthin** [comment]
what do you guys think @scusi @slavikm ?

**Comment by slavikm** [comment]
👍

**Comment by scusi** [comment]
I think we should merge. Slavik changes are good.
Am 13.10.2016 16:16 schrieb Willi Ballenthin <notifications@github.com>:what do you guys think @scusi @slavikm ?

**Comment by glaslos** [comment]
Any updates on this?

**Comment by williballenthin** [comment]
let's do this!

**Comment by williballenthin** [comment]
i've tagged and added a github release for the final commit prior to this merge: https://github.com/williballenthin/govt/releases/tag/v1.0

**Pull request merged**
