### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by slavikm**
Multiple fixes so that the client will be safer to use. See commit details.

### CODE REVIEW

**Comment by williballenthin** [comment]
Thanks for the contribution, @slavikm!

I'm a little hesitant to merge this entire changeset in one go, as it touches many parts of the code, and it changes the existing public API to `govt`. I'm worried that changing the API without warning will break people's existing tools that rely on this library.

Would you be willing to split these changes into smaller chunks, grouped by functionality? I'd really like to include many of them, especially the `http.Client` portion --- that's a great idea. Smaller pull requests will make it easier for us to review and discuss them.

As for things that change the public API, I'd be happy to work with you to either 1) find another way to achieve the intent without breaking changes, or 2) update the major revision number of the library and document an upgrade path.

**Comment by slavikm** [comment]
Hi @williballenthin,
Not sure how to go about breaking the changes to smaller chunks because most of them are related to the major change of making sure that the client is created / initialized in one go thus removing the room for error in creating a client and then forgetting to initialize it with apikey / tracing / logging / etc.
I know it's a change that breaks API but the codebase is pretty small and anyone using it should be able to change the code very quickly. I'm for bumping the version up - definitely be simpler for me than trying to somehow break the changes to multiple chunks :-)

**Comment by scusi** [comment]
Hi @williballenthin, @slavikm

First of all thank you @slavikm for your contribution to this codebase.
I enjoyed reading it and think it is a great improvement to the API.
 
@williballenthin i do understand why you hesitate to merge.

after thinking about the questions raised with this pull request (see above), 
i came to the following conclusion:

breaking the API is a harsh decision but keep going with an non improved API is also not very smart.
The API has to be broken in order to improve it and slavikm contribution is a clear improvement in many ways. Better break it now and not wait until even more code is based on it.

It was never actually stated anywhere but in my mind _govt_ had the status of _could be subject to changes_. 

The decision to break the existing API is hard but it does not get any better if we wait some longer. It will get worse. However before a merge we should maybe think about if we can come up with some sort of ordered transition plan. At least we should write some text to inform users what needs to be changed in coded that uses _govt_. We do have a blueprint already from the examples. I would write that up if no one else does that but i can not make any promises on when it will be ready.

**Comment by slavikm** [comment]
@scusi I believe that the only change I've introduced to users of the library is the initialization code. So, instead of creating a govt.Client with the relevant parameters, you should use the govt.New with the initialization functions.

@williballenthin - now that I think about it, I'm missing the license file for this project. I just assumed that this is a friendly MIT / BSD / Apache style license but I don't think it's specified anywhere, right?

**Comment by williballenthin** [comment]
@slavikm good question about licensing. Typically I release my code under Apache 2.0. Does that work for everyone in this thread (I think you are the most prolific contributors)?

**Comment by williballenthin** [comment]
@scusi I'm on board with your argument.

So, I think we'd better clearly define what changes are going to be made (in English, not code), and how they effect existing code. We can publish this short document as a new file referenced from the main README.md file. @slavikm, would you mind composing a few sentences that summarize any breaking changes?

While we're at it, can anyone think of other breaking changes that you'd like to see in the API?

**Comment by slavikm** [comment]
I think that from now, if we need to add more features or functionality, it
will be optional via the new OptionFunc configuration functions. I don't
see breaking changes of the top of my head right now. I will create a short
doc and commit it today.

**Comment by slavikm** [comment]
@williballenthin Regarding license - I'm fine with Apache 2.0.

**Comment by scusi** [comment]
me too.

Am 27.04.2015 19:57 schrieb Slavik Markovich:
> @williballenthin [1] Regarding license - I'm fine with Apache 2.0.

**Comment by glaslos** [comment]
I think those are some neat changes. Any plans to work on this @slavikm ? I would be also interested in helping out getting those changes merged.

**Comment by slavikm** [comment]
@glaslos sorry, I kind of forgot about this... I'm using my fork internally but I think it might be good to merge eventually.

**Comment by williballenthin** [comment]
I'm open to accepting the merge, if you're willing to share. Would expect everyone on this thread to provide feedback and discuss the changes, since you are the major users of this library.

**Pull request merged**
